coverage:
  paths:
    - ../lcov.info
  acceptable: current >= 60%
testExecutionTime:
  if: false
comment:
  if: is_pull_request
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
